name: Enigma
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2
  fluttertoast: ^3.1.0
  image_picker:  ^0.6.0+9
  shared_preferences: ^0.5.3+1
  firebase_storage: ^3.0.1
  cached_network_image: ^0.8.0
  intl: ^0.15.8
  diacritic: ^0.1.1
  sentry: ^2.2.0
  image_cropper: ^1.0.2
  contacts_service: ^0.2.4
  permission_handler: ^3.0.0
  share: ^0.6.1
  scoped_model: ^1.0.1
  local_auth: ^0.4.0+1
  crypto: ^2.0.6
  encrypt: ^3.0.0
  localstorage: ^1.2.0
  flutter_cache_manager: ^0.3.2
  photo_view: ^0.4.0
  mime: ^0.9.6+2
  ntp: ^1.0.3
  url_launcher: ^5.0.2
  launch_review: ^2.0.0
  flutter_secure_storage: ^3.2.1+1
  giphy_client: ^0.2.0
  firebase_messaging: ^5.0.2

dev_dependencies:
flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/img_not_available.jpeg
     - assets/flags/
     - assets/bg.png
     - assets/giphy.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
